-- 禁用 RLS 以便 anon key 可以读写（Admin Dashboard 使用）
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE faq_translations DISABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries DISABLE ROW LEVEL SECURITY;
ALTER TABLE page_views DISABLE ROW LEVEL SECURITY;
